version: "3"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postrgres
      POSTGRES_PASSWORD: postrgres

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html